title: Max Spevack
description: Senior Principal Linux Architect & Chief of Staff
theme: null
remote_theme: sproogen/modern-resume-theme
lang: en
version: 2

# Theme Settings
darkmode: true

# Personal Details
name: Max Spevack
title: Senior Principal Linux Architect
email: max.spevack@gmail.com
email_title: Email Me
about_profile_image: /max.jpg
github_username: maxspevack
linkedin_username: maxspevack

# Content Sections
content:
  - title: Experience
    layout: list
    content:
      - title: CIQ
        sub_title: July 2025 - Present
        link: https://ciq.com/
        description: |
          <div style="margin-bottom: 15px;">
            <div style="display: flex; justify-content: space-between;"><strong>Senior Principal Linux Architect</strong> <span>July 2025 - Present</span></div>
            <div style="display: flex; justify-content: space-between;"><strong>Chief of Staff to the CTO</strong> <span>July 2025 - Present</span></div>
          </div>
          The easiest way to describe my job is as CIQ's Linux <a href="https://en.wikipedia.org/wiki/Fixer_(person)">fixer</a> and as <a href="https://en.wikipedia.org/wiki/Consigliere">consigliere</a> to the CTO.
          <ul>
            <li>I served as interim leader of the Automation & Delivery team for five months, during which the team:
              <ul>
                <li>Launched an automated image build pipeline with customized schedules and kickoffs.</li>
                <li>Revamped secure boot signing automation and established an automated testing framework across all major cloud platforms.</li>
                <li>Improved image freshness metrics from quarterly to monthly.</li>
                <li>Produced customized images for <a href="https://cloud.google.com/distributed-cloud-air-gapped">Google Distributed Cloud</a>, AMD, and NVIDIA.</li>
              </ul>
            </li>
            <li>Drafted and helped implement a re-org creating the Release All Things (RAT) team alongside the Linux Engineering (LE) team.
              <ul>
                <li>LE is accountable for packages making it through the build system.</li>
                <li>RAT is accountable for everything required to assemble those packages into repositories and images and delivering those artifacts to customers.</li>
                <li>Led 2026 planning for the combined LE + RAT organization.</li>
              </ul>
            </li>
            <li>Hired the long-term Director for RAT and serve as coach/mentor and exception catcher for the RAT and Linux Engineering Directors.</li>
            <li>Established the engineering organization's weekly reporting framework, coordinated with Product on prioritization tracking, and automated the process using AI.</li>
          </ul>

      - title: Google
        sub_title: July 2021 - July 2023
        link: http://www.google.com/
        description: |
          <div style="margin-bottom: 15px;">
            <div style="display: flex; justify-content: space-between;"><strong>Senior Manager, <a href="https://cloud.google.com/compute/">Google Compute Engine</a></strong></div>
          </div>
          I formed and led the ~50 person GCE Fleet organization, owning the development, qualification, and release velocity of the kernel + hypervisor bundle running on all GCE hosts. The team owned the lifecycle and versioning of GCE host pools.
          <ul>
            <li>Assembly, qualification, deployment, and operation of the standard GCE fleet, with a primary focus on velocity and heterogeneity metrics to inform our engineering priorities. One innovation was the amusingly named “mandatory experiments” policy to reduce rollbacks.</li>
            <li>Development, initial deployment, and operation of a “stable fleet” for enterprise customers with greater sensitivities to change windows. This functionality included automated notifications, migration window (with live and managed migrations), and specific rate-of-change guarantees. Later, this stable fleet concept expanded to fine-grained GCE host pools.</li>
            <li>White-gloves engineering treatment for ultra-VIP GCE customers.</li>
          </ul>

      - title: Amazon Web Services
        sub_title: July 2019 - June 2021
        link: http://aws.amazon.com/
        description: |
          <div style="margin-bottom: 15px;">
            <div style="display: flex; justify-content: space-between;"><strong>General Manager, <a href="https://aws.amazon.com/linux/amazon-linux-2023/">Amazon Linux</a></strong> <span>July 2019 - June 2021</span></div>
            <div style="display: flex; justify-content: space-between;"><strong>Senior Manager, <a href="https://aws.amazon.com/opensource/">Open Source</a></strong> <span>July 2019 - June 2021</span></div>
          </div>
          I led the >100 person organization that owned Amazon Linux – available as a <a href="https://aws.amazon.com/amazon-linux-ami/">public EC2 image</a> and as an internal server OS for both <a href="http://aws.amazon.com/">AWS</a> and Amazon's <a href="http://www.amazon.com/">retail business</a> – as well as Amazon’s <a href="https://en.wikipedia.org/wiki/Open_Source_Program_Office">Open Source Program Office</a> (OSPO).
          <br><br>
          I was ultimately accountable for Amazon’s Linux portfolio – product and engineering, including:
          <ul>
            <li>Creation of the <a href="https://aws.amazon.com/amazon-linux-ami/">Amazon Linux 1</a> (AL1) <a href="https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/">extended support plan</a> based on many customer requests.</li>
            <li>Continued development of <a href="https://aws.amazon.com/amazon-linux-ami/">Amazon Linux 2</a> (AL2), including the addition of <a href="https://docs.aws.amazon.com/linux/al2/ug/al2-live-patching.html">kernel live patching</a>.</li>
            <li>Delivered the fully-approved PR/FAQ for <a href="https://aws.amazon.com/linux/amazon-linux-2023/">Amazon Linux 2023</a>.</li>
            <li>Launched GA of <a href="https://bottlerocket.dev/">Bottlerocket</a>, a Linux-based OS purpose-built for hosting containers on multiple platforms (AWS, Bare Metal, VMWare) as well as orchestrators (EKS, ECS).</li>
            <li>Prioritized internal migration to AL2 by delivering in-place upgrades from AL1.</li>
            <li>Rebuilt the CVE ingestion infrastructure, improving Amazon Linux security tracking and <a href="https://alas.aws.amazon.com/">publication</a>.</li>
          </ul>
          With the OSPO, I re-organized the team to take a tooling-based approach to its charter, with a specifically increasing the number of cases (including GitHub administration and M&A work) that could be resolved either automatically or by customers directly and creating tooling to reduce the team’s manual labor.
          <ul>
            <li>Launched “Open Source Champions”, a program to deputize Principal Engineers in organizations to make open-source related decisions directly, pushing ownership to the customer.</li>
            <li>Delivered and received approval from AWS leadership on “Open Source Decision Making Guidelines”, a mechanism for teams to determine if and when to open source their code.</li>
            <li>Developed and operationalized an “Open Source Readiness Review”, ensuring that teams making the decision to open source their code had done so in a way that would result in successful community projects, bolstering Amazon’s open source reputation.</li>
          </ul>

      - title: Google
        sub_title: February 2016 - June 2019
        link: http://www.google.com/
        description: |
          <div style="margin-bottom: 15px;">
            <div style="display: flex; justify-content: space-between;"><strong>Senior Manager, <a href="https://cloud.google.com/compute/">Google Compute Engine</a></strong></div>
          </div>
          I led the three GCE engineering teams accountable for:
          <ul>
            <li>KVM, both in Google's kernel and the relationship with the upstream community.</li>
            <li>Building, qualifying, and measuring GCE host kernel quality and deployment velocity.</li>
            <li>New product introduction and end-to-end customer experience for CPUs, GPUs, memory-optimized instances, and nested virtualization.</li>
            <li>Live migration functionality and efficiency.</li>
          </ul>
          Customer-facing launches include <a href="https://cloud.google.com/blog/products/gcp/compute-engine-updates-bring-skylake-ga-extended-memory-and-more-vm-flexibility">Skylake</a> and <a href="https://cloud.google.com/blog/products/compute/introducing-compute-and-memory-optimized-vms-for-google-compute-engine">Cascade Lake</a> CPUs, SAP-certified large memory instances (<a href="https://cloud.google.com/blog/products/gcp/now-shipping-ultramem-machine-types-with-up-to-4tb-of-ram">ultramem</a>, <a href="https://cloud.google.com/blog/products/compute/introducing-compute-and-memory-optimized-vms-for-google-compute-engine">m2</a>), Nvidia GPUs (<a href="https://cloud.google.com/blog/products/compute/tesla-v100-gpus-are-now-generally-available">V100</a>, <a href="https://cloud.google.com/blog/products/gcp/introducing-nvidia-tesla-p4-gpus-accelerating-virtual-workstations-and-ml-inference-compute-engine">P4 with GRID support</a>, <a href="https://cloud.google.com/blog/products/compute/efficiently-scale-ml-and-other-compute-workloads-on-nvidias-t4-gpu-now-generally-available">T4</a>), and <a href="https://cloud.google.com/blog/products/gcp/introducing-nested-virtualization-for">nested virtualization</a>. The team received four of Google's "Cloud Feat of Engineering" awards for response to <a href="https://blog.google/products/google-cloud/answering-your-questions-about-meltdown-and-spectre/">Spectre / Meltdown</a>, response to <a href="https://cloud.google.com/blog/products/gcp/protecting-against-the-new-l1tf-speculative-vulnerabilities">L1TF</a>, nested virtualization, and the SAP-certified large-memory instances.

      - title: Amazon Web Services
        sub_title: August 2011 - January 2016
        link: http://aws.amazon.com/
        description: |
          <div style="margin-bottom: 15px;">
            <div style="display: flex; justify-content: space-between;"><strong>Manager, Linux Kernel & Operating Systems</strong></div>
          </div>
          I led the team accountable for Amazon Linux. The team's primary objective was to build, qualify, deploy, and support multiple versions of Amazon Linux. This included <a href="https://aws.amazon.com/amazon-linux-ami/2015.09-release-notes/">feature</a> <a href="https://aws.amazon.com/amazon-linux-ami/2015.03-release-notes/">development</a> and integration with EC2, building kernel and userspace packages, <a href="https://alas.aws.amazon.com/">security updates</a>, and deploying packages and images. The team owned the infrastructure and tooling to build packages, compose images, stage repositories, perform automated testing, and gather metrics.
          <br><br>
          I spent a year simultaneously managing two distinct teams – the Amazon Linux team discussed above, and the team responsible for qualifications of new <a href="https://aws.amazon.com/ec2/instance-types/">EC2 instance types</a> and platforms. During that time, the qualifications team developed tooling, test coverage, and reporting for the <a href="https://aws.amazon.com/blogs/aws/low-cost-burstable-ec2-instances/">T2</a>, <a href="https://aws.amazon.com/blogs/aws/now-available-new-c4-instances/">C4</a>, and <a href="https://aws.amazon.com/blogs/aws/next-generation-of-dense-storage-instances-for-ec2/">D2</a> launches. I assisted with the hiring of a manager to transition the qualifications team over to, and I helped with onboarding, training, and a smooth handoff of responsibilities. I also spent 18 months as part of the EC2 Operations team. I was responsible for a weekly summary of all EC2 operational issues including discussion of customer impacting events, status of key metrics, and overall EC2 fleet health.

      - title: Red Hat
        sub_title: August 2004 - August 2011
        link: http://www.redhat.com/
        description: |
          <div style="margin-bottom: 15px;">
            <div style="display: flex; justify-content: space-between;"><strong>Manager, Open Source Community Architecture</strong> <span>Feb 2008 - Aug 2011</span></div>
            <div style="display: flex; justify-content: space-between;"><strong><a href="https://docs.fedoraproject.org/en-US/council/fpl/">Fedora Project Leader</a></strong> <span>Feb 2006 - Feb 2008</span></div>
            <div style="display: flex; justify-content: space-between;"><strong>Linux Systems Engineer</strong> <span>Aug 2004 - Feb 2006</span></div>
          </div>
          I was ultimately accountable for the <a href="https://getfedora.org/">Fedora Project</a>, a collaboration between Red Hat and a worldwide community of free software contributors whose flagship project is the <a href="http://en.wikipedia.org/wiki/Fedora_(operating_system)">Fedora Linux distribution</a>. I was responsible for Red Hat employees and community contributors in numerous areas: product and engineering, operations, marketing, branding, community, communications, public speaking (<a href="http://lwn.net/Articles/237700/">LWN</a>, <a href="https://slashdot.org/story/06/08/17/177220/fedora-project-leader-max-spevack-responds">Slashdot</a>, <a href="http://www.youtube.com/watch?v=JC6URXglbO4">Ohio Linux Fest</a>), legal, financial, budgeting, and hiring.
          <br><br>
          After two years I split the role into several parts – a continued Fedora Project Leader, a new Fedora Engineering Manager, and a new Open Source Community Architecture team, which I led. This was a global team, with a charter to deliver highly leveraged growth, development, and success of communities strategic to Red Hat's business and brand, including:
          <ul>
            <li>Ensuring that the free software community was an equal partner in the creation of Red Hat's products, and that the <a href="http://www.theopensourceway.org/">Open Source Way</a> was institutionalized in Red Hat’s culture.</li>
            <li>Stewardship and senior-level leadership of the Fedora Project.</li>
            <li>Merging the Open Source Way and education, founding the <a href="http://teachingopensource.org/">Teaching Open Source</a> community.</li>
          </ul>

      - title: Verisign
        sub_title: October 2002 - August 2004
        link: http://en.wikipedia.org/wiki/Verisign
        description: |
          <div style="margin-bottom: 15px;">
            <div style="display: flex; justify-content: space-between;"><strong>Quality Assurance Engineer</strong></div>
          </div>

      - title: Stanford University
        sub_title: September 1998 - June 2002
        link: http://cs.stanford.edu/
        description: |
          <div style="margin-bottom: 15px;">
            <div style="display: flex; justify-content: space-between;"><strong>BS <a href="http://cs.stanford.edu/">Computer Science</a></strong></div>
          </div>

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-remote-theme
