title: Max Spevack
description: Senior Principal Linux Architect & Chief of Staff
theme: null
remote_theme: sproogen/modern-resume-theme
lang: en

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme